# Generated by Django 5.1.7 on 2025-03-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_crm_model_complete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_model',
            name='complete_date',
            field=models.DateField(null=True),
        ),
    ]
